import { ColumnDescriptor } from "../interfaces/ColumnDescriptor"

export const parteProducto: ColumnDescriptor[] = [

    {
      title: "IDPARTE",
      idInput: "idParte",
      value: "1",
      content: "",
      type: "noInput",
      editable: true,
      visible:true,
      defaultValue: "1",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "INDICE PRODUCTO",
      idInput: "indiceProducto",
      value: "1",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      defaultValue: "1",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "BAMBURI",
      idInput: "bamburi",
      value: "",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      defaultValue: "",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "OPERARIO",
      idInput: "operario",
      value: "1",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      defaultValue: "1",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "PASADA",
      idInput: "pasada",
      value: "1",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      defaultValue: "1",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "TIPO",
      idInput: "tipo",
      value: "",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      additionalStyles: "",
      defaultValue: "",
      options: [],
      placeHolder: ""
    },
    {
      title: "COLOR",
      idInput: "color",
      value: "",
      content: "",
      type: "noInput",
      editable: false,
      visible:true,
      defaultValue: "",
      additionalStyles: "",
      options: [],
      placeHolder: ""
    },
    {
      title: "MOLDE",
      idInput: "molde",
      content: "",
      value: "",
      type: "noInput",
      editable: false,
      visible:true,
      additionalStyles: "",
      defaultValue: "",
      options: [],
      placeHolder: ""
    },
    {
      title: "PLANCH OB.",
      idInput: "planchaobtenidas",
      content: "",
      value: "",
      type: "noInput",
      editable: false,
      visible:true,
      additionalStyles: "",
      defaultValue: "",
      options: [],
      placeHolder: ""
    },
    {
      title: "PESO",
      idInput: "peso",
      type: "noInput",
      content: "",
      value: "",
      editable: false,
      visible:true,
      defaultValue: "",
      options: [""],
      additionalStyles: "",
      placeHolder: ""
    },
    {
      title: "FORMULAS",
      idInput: "formulas",
      type: "noInput",
      content: "",
      value: "",
      editable: false,
      visible:true,
      defaultValue: "",
      options: [""],
      additionalStyles: "",
      placeHolder: ""
    },
    {
      title: "PLANCHAS",
      idInput: "planchas",
      type: "noInput",
      content: "",
      value: "",
      editable: false,
      visible:true,
      defaultValue: "",
      options: [""],
      additionalStyles: "",
      placeHolder: ""
    },
    {
      title: "ACELERANTES",
      idInput: "acelerantes",
      type: "noInput",
      content: "",
      value: "",
      editable: false,
      visible:true,
      defaultValue: "",
      additionalStyles: "",
      options: [""],
      placeHolder: ""
    },
    {
      title: "Editar",
      idInput: "Editar",
      content: "",
      value: "",
      type: "svg",
      editable: false,
      visible:true,
      additionalStyles: "",
      options: [],
      placeHolder: ""
    },
    {
        title: "Borrar",
        idInput: "Borrar",
        content: "borrar",
        value: "",
        type: "svg",
        editable: false,
        visible:true,
        additionalStyles: "",
        options: [],
        placeHolder: ""
      }
  ]