import { ColumnDescriptor } from "../interfaces/ColumnDescriptor"

export const PlantillaProductoInventario: ColumnDescriptor[] = [
  {
    title: "idProducto",
    idInput: "idProducto",
    value: "1",
    content: "",
    type: "noInput",
    editable: true,
    visible: true,
    defaultValue: "1",
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  },
  {
    title: "FECHAENTRADA",
    idInput: "fechaEntrada",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "FECHASALIDA",
    idInput: "fechaSalida",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "PLANCHA",
    idInput: "plancha",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "COLOR",
    idInput: "color",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "DIBUJO",
    idInput: "dibujo",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "MOLDE",
    idInput: "molde",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "CALIBRE",
    idInput: "calibre",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "ACABADO01",
    idInput: "acabado01",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "ACABADO02",
    idInput: "acabado02",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "STOCK",
    idInput: "stock",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: 0,
    options:[],
    placeHolder: ""
  },
  {
    title: "cantidadEntrante",
    idInput: "cantidadEntrante",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: 1,
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  },
  {
    title: "cantidadSalida",
    idInput: "cantidadSalida",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  },
  {
    title: "Entradas",
    idInput: "entradas",
    content: "E",
    value: "",
    type: "button",
    editable: false,
    visible: true,
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "Salidas",
    idInput: "salidas",
    content: "S",
    value: "",
    type: "button",
    editable: false,
    visible: true,
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
      title: "Borrar",
      idInput: "Borrar",
      content: "",
      value: "",
      type: "svg",
      editable: false,
      visible:true,
      additionalStyles: "",
      options: [],
      placeHolder: ""
   }
]
