import { ColumnDescriptor } from "../interfaces/ColumnDescriptor"

export const ResumenProductoInventario: ColumnDescriptor[] = [
  {
    title: "idProducto",
    idInput: "idProducto",
    value: "1",
    content: "",
    type: "noInput",
    editable: true,
    visible: true,
    defaultValue: "1",
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  },
  {
    title: "FECHAENTRADA",
    idInput: "fechaEntrada",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "PLANCHAS",
    idInput: "planchas",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "COLOR",
    idInput: "color",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "DIBUJO",
    idInput: "dibujo",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "MOLDE",
    idInput: "molde",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "CALIBRE",
    idInput: "calibre",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "ACABADO01",
    idInput: "acabado01",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: false,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "ACABADO02",
    idInput: "acabado02",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: false,
    additionalStyles: "",
    defaultValue: "",
    options: [],
    placeHolder: ""
  },
  {
    title: "STOCK",
    idInput: "stock",
    content: "",
    value: "",
    type: "noInput",
    editable: false,
    visible: true,
    additionalStyles: "",
    defaultValue: 0,
    options:[],
    placeHolder: ""
  },
  {
    title: "cantidadEntrante",
    idInput: "cantidadEntrante",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: 1,
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  },
  {
    title: "cantidadSalida",
    idInput: "cantidadSalida",
    value: "",
    content: "",
    type: "noInput",
    editable: false,
    visible: true,
    defaultValue: "",
    additionalStyles: "",
    options: [""],
    placeHolder: ""
  }
]
